# Generated by Django 5.1.2 on 2024-10-21 01:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('Bus', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('v_nom', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('carrier', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('control', models.CharField(max_length=255)),
                ('generator', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('v_mag_pu_set', models.FloatField()),
                ('v_mag_pu_min', models.FloatField()),
                ('v_mag_pu_max', models.FloatField()),
                ('sub_network', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'buses',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('Line', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bus0', models.CharField(max_length=255)),
                ('bus1', models.CharField(max_length=255)),
                ('num_parallel', models.FloatField()),
                ('length', models.FloatField()),
                ('carrier', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('s_max_pu', models.FloatField()),
                ('s_nom', models.FloatField()),
                ('capital_cost', models.FloatField()),
                ('x', models.FloatField()),
                ('r', models.FloatField()),
                ('b', models.FloatField()),
                ('x_pu_eff', models.FloatField()),
                ('r_pu_eff', models.FloatField()),
                ('s_nom_opt', models.FloatField()),
                ('v_nom', models.FloatField()),
                ('g', models.FloatField()),
                ('s_nom_extendable', models.BooleanField()),
                ('s_nom_min', models.FloatField()),
                ('s_nom_max', models.FloatField()),
                ('build_year', models.BigIntegerField()),
                ('lifetime', models.FloatField()),
                ('terrain_factor', models.FloatField()),
                ('v_ang_min', models.FloatField()),
                ('v_ang_max', models.FloatField()),
                ('sub_network', models.CharField(max_length=255)),
                ('x_pu', models.FloatField()),
                ('r_pu', models.FloatField()),
                ('g_pu', models.FloatField()),
                ('b_pu', models.FloatField()),
                ('country_code', models.CharField(max_length=10)),
                ('x_0', models.FloatField()),
                ('y_0', models.FloatField()),
                ('x_1', models.FloatField()),
                ('y_1', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='TotalDemand',
            fields=[
                ('country_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_demand_twh', models.FloatField()),
            ],
            options={
                'db_table': 'total_demand',
            },
        ),
        migrations.CreateModel(
            name='GenerationMix',
            fields=[
                ('carrier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('generation_twh', models.FloatField()),
                ('country_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'generation_mix',
                'unique_together': {('carrier', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='TotalGenerationByAcBus',
            fields=[
                ('bus', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrier', models.CharField(max_length=255)),
                ('generation', models.FloatField()),
                ('country_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'total_generation_by_ac_bus',
                'unique_together': {('bus', 'carrier')},
            },
        ),
    ]
